# Generated by Django 2.1.5 on 2021-08-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diawe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='aUser',
        ),
    ]
